import "../styles/globals.css";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { SongContextProvider } from "../context";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <SongContextProvider>
        <Layout>
          <Head>
            <title>Musica</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/musica-logo.png" />
          </Head>

          <Component {...pageProps} />
        </Layout>
      </SongContextProvider>
    </>
  );
}

export default MyApp;
